config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'users#index'

    resources :users
    resources :occupations
    resources :books
    resources :companies
    resources :vehicles
    resources :cities
    resources :countries
    resources :houses
    resources :clothes
    resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true,
   length: { minimum: 5 }
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true,
  length: { minimum: 4 }
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  validates :name, presence: true,
  length: { minimum: 4 }
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :industry, presence: true,
  length: { minimum: 5 }
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :part_of_africa, presence: true,
  length: { minimum: 4 }
end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, :subject, :professor,
  length: { minimum: 4 }
end

app/models/house.rb
class House < ApplicationRecord

  validates :city, :has_garage, presence: true,
  length: { minimum: 3 } 
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  validates :title, presence: true,
   length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, presence: true,
    length: { minimum: 5}
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :make, :model, presence: true,
  length: { minimum: 5 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

      def index
          @users = User.all
      end

      def show
        @user = User.find(params[:id])
      end

      def new
          @user = User.new
      end

      def edit
          @user = User.find(params[:id])
      end

      def create
          @user = User.new(user_params)

              if @user.save
                redirect_to @user
            else
                render 'new'
            end
      end

      def update
        @user = User.find(params[:id])

            if @user.update(user_params)
              redirect_to @user
            else
              render 'edit'
            end
      end

      def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to users_path

      end

     private
       def user_params
         params.require(:user).permit(:first_name, :last_name)

       end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

    <p>
          <%= form.label :'first name' %><br>
          <%= form.text_field :first_name %>
    </p>

    <p>
          <%= form.label :'last name'  %><br>
          <%= form.text_field :last_name %>
    </p>

   <%= form.submit  %>

<% end %>

app/views/users/edit.html.erb
<h3>Edit list</h3>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>users list</h1>

<%= link_to 'new_user', new_user_path %> <br>

<table>
      <tr>
         <th>Name</th>
         <th>Surname</th>
      </tr>

    <%  @users.each do |user| %>
      <tr>
          <td><%= user.id%></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user_path(user),
            method: :delete,
            data: {confirm: 'Are yuh sure ?'}%></td>
      </tr>
   <% end %>

</table>


<table>
  <tr>
    <td><%= link_to 'Occupations', occupations_path %> <br></td>
    <td><%= link_to 'Books', books_path %> <br></td>
    <td><%= link_to 'Companies', companies_path %> <br></td>
  </tr>

  <tr>
    <td><%= link_to 'Vehicles', vehicles_path %> <br></td>
    <td><%= link_to 'Cities', cities_path %> <br></td>
    <td><%= link_to 'Countries', countries_path %> <br></td>
  </tr>

  <tr>
    <td><%= link_to 'Houses', houses_path %> <br></td>
    <td><%= link_to 'clothes', clothes_path %> <br></td>
    <td><%= link_to 'Courses', courses_path %> <br></td>
  </tr>

</table>

app/views/users/new.html.erb
<h3>Edit list</h3>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h2>entered user</h2>
<p>
    <%= @user.first_name %>
    <%= @user.last_name %>
</p>

<%= link_to 'index', users_path%>