config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'users#index'

    resources :users
    resources :occupations
    resources :books
    resources :companies
    resources :vehicles
    resources :cities
    resources :countries
    resources :houses
    resources :clothes
    resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true,
   length: { minimum: 5 }
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true,
  length: { minimum: 4 }
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  validates :name, presence: true,
  length: { minimum: 4 }
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :industry, presence: true,
  length: { minimum: 5 }
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :part_of_africa, presence: true,
  length: { minimum: 4 }
end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, :subject, :professor,
  length: { minimum: 4 }
end

app/models/house.rb
class House < ApplicationRecord

  validates :city, :has_garage, presence: true,
  length: { minimum: 3 } 
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  validates :title, presence: true,
   length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, presence: true,
    length: { minimum: 5}
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :make, :model, presence: true,
  length: { minimum: 5 }
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

  def index
    @clothes = Clothe.all

  end

 def show
     @clothe = Clothe.find(params[:id])
 end

  def new
      @clothe = Clothe.new
  end

  def edit
      @clothe = Clothe.find(params[:id])
  end

  def create
     @clothe = Clothe.new(clothe_params)

     if @clothe.save
        redirect_to @clothe
     else
        render 'new'
     end
  end

  def update
     @clothe = Clothe.find(params[:id])
     if @clothe.update(clothe_params)
        redirect_to @clothe
     else
        render 'edit'
     end
  end

  def destroy
    @clothe = Clothe.find(params[:id])
    @clothe.destroy

    redirect_to clothes_path
  end

  private
    def clothe_params
       params.require(:clothe).permit(:name, :piece)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/clothes/_form.html.erb
<%= form_with(model: @clothe, lacal: true) do |form|%>

  <p>
      <%= form.label :Name %> <br>
      <%= form.text_field :name%>
  </p>

  <p>
      <%= form.label :piece %> <br>
      <%= form.text_field :piece%>
  </p>

   <p>
        <%= form.submit %>
   </p>
<% end %>

app/views/clothes/edit.html.erb
<h4>Edit clothe data</h4>

<%= render 'form' %>

app/views/clothes/index.html.erb
<h4>Clothing list</h4>

<%= link_to 'new', new_clothe_path%>

<table>
    <tr>
        <th>id</th>
        <th>Name</th>
        <th>Piece</th>
    </tr>

    <% @clothes.each do |clothe|%>
       <tr>
           <td><%= clothe.id %></td>
           <td><%= clothe.name %></td>
           <td><%= clothe.piece %></td>
           <td><%= link_to 'Show', clothe_path(clothe) %></td>
           <td><%= link_to 'edit', edit_clothe_path(clothe) %></td>
           <td><%= link_to 'Delete', clothe_path(clothe),
             method: :delete,
             data: {confirm: 'Are yuh sure ?'}
             %></td>
       </tr>
    <% end %>
</table>

<%= link_to 'Courses', courses_path %> <br>
<%= link_to 'index', users_path %> <br>

app/views/clothes/new.html.erb
<h4>Add new clothe data</h4>

<%= render 'form' %>

app/views/clothes/show.html.erb
<h4>Entered details</h4>

<%= @clothe.name %> <br>
<%= @clothe.piece %> <br>

<%= link_to 'index', clothes_path%>