config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'users#index'

    resources :users
    resources :occupations
    resources :books
    resources :companies
    resources :vehicles
    resources :cities
    resources :countries
    resources :houses
    resources :clothes
    resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true,
   length: { minimum: 5 }
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true,
  length: { minimum: 4 }
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  validates :name, presence: true,
  length: { minimum: 4 }
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :industry, presence: true,
  length: { minimum: 5 }
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :part_of_africa, presence: true,
  length: { minimum: 4 }
end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, :subject, :professor,
  length: { minimum: 4 }
end

app/models/house.rb
class House < ApplicationRecord

  validates :city, :has_garage, presence: true,
  length: { minimum: 3 } 
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  validates :title, presence: true,
   length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, presence: true,
    length: { minimum: 5}
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :make, :model, presence: true,
  length: { minimum: 5 }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def index
      @companies = Company.all

    end

    def show
          @company = Company.find(params[:id])
    end

    def new
        @company = Company.new
    end

    def edit
        @company = Company.find(params[:id])
    end

    def create
          @company = Company.new(company_params)
          if @company.save

          redirect_to @company
        else
          render 'new'
        end
    end

    def update
      @company = Company.find(params[:id])

      if @company.update(company_params)
        redirect_to @company
      else
        render 'edit'
      end
    end

    def destroy
      @company = Company.find(params[:id])
      @company.destroy

      redirect_to companies_path

    end


    private
        def company_params
              params.require(:company).permit(:name, :industry)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>

      <p>
            <%= form.label :Name %> <br>
            <%= form.text_field :name %>
      </p>


       <p>
            <%= form.label :Industry %> <br>
            <%= form.text_field :industry %>
       </p>

       <p>
            <%= form.submit %>
       </p>
<% end %>

app/views/companies/edit.html.erb
<h3>Edit details</h3>

<%= render 'form' company: @company %>

app/views/companies/index.html.erb
<h3>Company list</h3>
<%= link_to 'new', new_company_path %>
  <table>
        <tr>
              <th>Name</th>
              <th>Industry</th>
        </tr>
   <% @companies.each do |company| %>
        <tr>
              <td><%= company.name %></td>
              <td><%= company.industry %></td>
              <td><%= link_to 'Show', company_path(company) %></td>
              <td><%= link_to 'edit', edit_company_path(company) %></td>
              <td><%= link_to 'Delete', company_path(company),
                method: :delete,
                data: {confirm: 'Are yuh sure ?'}
                %></td>

        </tr>
    <% end %>
  </table>

<%= link_to 'Vehicle', vehicles_path %> <br>
<%= link_to 'index', users_path %> <br>

app/views/companies/new.html.erb
<h3>new Company details</h3>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<h3>entered company's details</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Industry</th>
  </tr>

   <tr>
        <td><%= @company.name %> </td>
        <td><%= @company.industry %></td>
   </tr>

</table>

<%= link_to 'index', companies_path %>