config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'users#index'

    resources :users
    resources :occupations
    resources :books
    resources :companies
    resources :vehicles
    resources :cities
    resources :countries
    resources :houses
    resources :clothes
    resources :courses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true,
   length: { minimum: 5 }
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true,
  length: { minimum: 4 }
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  validates :name, presence: true,
  length: { minimum: 4 }
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :industry, presence: true,
  length: { minimum: 5 }
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :part_of_africa, presence: true,
  length: { minimum: 4 }
end

app/models/course.rb
class Course < ApplicationRecord

  validates :name, :subject, :professor,
  length: { minimum: 4 }
end

app/models/house.rb
class House < ApplicationRecord

  validates :city, :has_garage, presence: true,
  length: { minimum: 3 } 
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  validates :title, presence: true,
   length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, presence: true,
    length: { minimum: 5}
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :make, :model, presence: true,
  length: { minimum: 5 }
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

      def index
          @vehicles = Vehicle.all
      end

      def show
         @vehicle = Vehicle.find(params[:id])
      end

      def new
          @vehicle = Vehicle.new
      end

      def edit
          @vehicle = Vehicle.find(params[:id])
      end

      def create
          @vehicle = Vehicle.new(vehicle_params)

          if @vehicle.save
             redirect_to @vehicle
          else
            render 'new'
          end
      end

      def update
          @vehicle = Vehicle.find(params[:id])

          if @vehicle.update(vehicle_params)
             redirect_to vehicles_path
          else
             render 'edit'
          end
      end

      def destroy
        @vehicle = Vehicle.find(params[:id])
        @vehicle.destroy

        redirect_to vehicles_path
      end

private
   def vehicle_params
     params.require(:vehicle).permit(:make, :model, :year)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: @vehicle, lacal: true) do |form| %>

    <p>
        <%= form.label :Make %> <br>
        <%= form.text_field :make %>
    </p>

    <p>
        <%= form.label :Model %> <br>
        <%= form.text_field :model %>
    </p>

    <p>
        <%= form.label :Year %> <br>
        <%= form.text_field :year %>
    </p>

   <p>
          <%= form.submit %>
   </p>

<% end %>

app/views/vehicles/edit.html.erb
<h4>Edit Vehicle data</h4>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<h3>Vehicle list</h3>

<%= link_to 'new', new_vehicle_path %>

<table>
    <tr>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
    </tr>

  <% @vehicles.each do |vehicle| %>
        <tr>
           <td><%= vehicle.make %></td>
           <td><%= vehicle.model %></td>
           <td><%= vehicle.year %></td>
           <td><%= link_to 'show', vehicle_path(vehicle) %></td>
           <td><%= link_to 'edit', edit_vehicle_path(vehicle) %></td>
           <td><%= link_to 'delete', vehicle_path(vehicle),
                    method: :delete,
                    data: {confirm: 'Are yuh sure ?'}
              %></td>
        </tr>
  <% end %>
</table>

<%= link_to 'Cities', cities_path %> <br>
<%= link_to 'index', users_path %> <br>

app/views/vehicles/new.html.erb
<h4>enter vehicle details</h4>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<h4>entered details</h4>

<%= @vehicle.make %> <br>
<%= @vehicle.model %> <br>
<%= @vehicle.year %> <br>

<%= link_to 'index', vehicles_path %>